### ISSUE TITLE
My generated dart file is getting errors like missing_const_final_var_or_type and implicit_this_reference_in_initializer

### ISSUE THREAD

**Issue by Cronnay** [brickpop/flutter-rust-ffi#31]
Hi!

Copied this example. My pubspec:
```
dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: 4.1.3

ffigen:
  name: NativeLibrary
  description: Bindings to `headers/example.h`.
  output: 'lib/generated_bindings.dart'
  headers:
    entry-points:
      - 'rust/bindings.h'
```

My header is only 1 row and is: `void start_application(void);`. 
So when I run `flutter pub run ffigen` it creates a dart file with errors like: `Variables must be declared using the keywords 'const', 'final', 'var' or a type name. Try adding the name of the type of the variable or the keyword 'var'.` and then `The instance member '_start_applicationPtr' can't be accessed in an initializer. Try replacing the reference to the instance member with a different expression`

Any clue why I get these errors?
